import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'




// utils:
import { handleDragOver } from '@/utils/onDragOver';
import { handleDragLeave } from '@/utils/handleDragLeave';
import { handleDrop } from '@/utils/handleDrop';








export default function Home() {



















  return (
    <>
      <Head>
        <title>Simple drag and drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Draggie & Droppie</h1>


      {/* container */}
        <form className={styles.container}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            method='POST'
            >


              drop here


        <input type="file"  hidden
        />
        {/* <label htmlFor="uploadButton" className={styles.label}>Upload here</label> */}






        </form>
      </main>
    </>
  )
}
