import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'




// utils:
import { handleDragOver } from '@/utils/onDragOver';
import { handleDragLeave } from '@/utils/handleDragLeave';
import { handleDrop } from '@/utils/handleDrop';








export default function Home() {



















  return (
    <>
      <Head>
        <title>Simple drag and drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>


<div className={styles.wrapper}>


      <p className={styles.header}>WAV FILE x-TRACTOR</p>

      {/* container */}
        <form className={styles.container}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            method='POST'
            >


              <p>Drag File </p>


        <input type="file"  hidden
        />




        </form>
        </div>
      </main>
    </>
  )
}
